# Site settings
title: "Dissertation Drafts"
description: "Listing of dissertation builds"
baseurl: "/dissertation" # begin with /repo-name if use as project, else leave empty for gh-pages
url: "" # default is empty
author: "Richard Joyce"

# Build settings
kramdown:
  input: GFM
permalink: pretty

plugins:
- jemoji
- jekyll-feed

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname:

theme: jekyll-theme-leap-day